export const TUS_SUBJECTS = [
  "Anatomi",
  "Fizyoloji - Histoloji - Embriyoloji",
  "Tıbbi Biyokimya",
  "Tıbbi Mikrobiyoloji",
  "Tıbbi Patoloji",
  "Tıbbi Farmakoloji",
  "Dahiliye",
  "Pediatri",
  "Genel Cerrahi",
  "Kadın Doğum",
  "Küçük Stajlar",
] as const;

export const TUS_SUBJECTS_WITH_OTHER = [...TUS_SUBJECTS, "Diğer"] as const;

export type TusSubject = (typeof TUS_SUBJECTS)[number];
export type TusSubjectOrOther = (typeof TUS_SUBJECTS_WITH_OTHER)[number];

export const TUS_SUBJECT_COLORS: Record<TusSubjectOrOther, string> = {
  Anatomi: "#6366f1",
  "Fizyoloji - Histoloji - Embriyoloji": "#0ea5e9",
  "Tıbbi Biyokimya": "#8b5cf6",
  "Tıbbi Mikrobiyoloji": "#10b981",
  "Tıbbi Patoloji": "#ef4444",
  "Tıbbi Farmakoloji": "#f59e0b",
  Dahiliye: "#14b8a6",
  Pediatri: "#ec4899",
  "Genel Cerrahi": "#f97316",
  "Kadın Doğum": "#fb7185",
  "Küçük Stajlar": "#64748b",
  Diğer: "#94a3b8",
};

export const TUS_SUBJECT_BADGES: Record<
  TusSubjectOrOther,
  "default" | "secondary" | "success" | "warning" | "destructive"
> = {
  Anatomi: "secondary",
  "Fizyoloji - Histoloji - Embriyoloji": "success",
  "Tıbbi Biyokimya": "secondary",
  "Tıbbi Mikrobiyoloji": "success",
  "Tıbbi Patoloji": "destructive",
  "Tıbbi Farmakoloji": "warning",
  Dahiliye: "success",
  Pediatri: "default",
  "Genel Cerrahi": "warning",
  "Kadın Doğum": "secondary",
  "Küçük Stajlar": "default",
  Diğer: "secondary",
};

export const TUS_TOPIC_GROUPS = [
  {
    name: "Anatomi",
    subtopics: [
      "Kemikler",
      "Eklemler",
      "Kaslar",
      "Solunum Sistemi",
      "Dolaşım Sistemi",
      "Gastrointestinal Sistem",
      "Ürogenital Sistem",
      "Nöroanatomi",
    ],
  },
  {
    name: "Fizyoloji - Histoloji - Embriyoloji",
    subtopics: [
      "Hücre",
      "Doku",
      "Kas",
      "Genital Sistem ve Genel Embriyoloji",
      "Hemopoetik Sistem",
      "Gastrointestinal Sistem",
      "Kardiyovasküler Sistem",
      "Endokrin Sistem",
      "Solunum Sistemi",
      "Sinir Sistemi",
      "Üriner Sistem",
    ],
  },
  {
    name: "Tıbbi Biyokimya",
    subtopics: [
      "Hücre ve Organeller",
      "Metabolizma",
      "Karbonhidratlar",
      "Lipitler",
      "Aminoasitler ve Proteinler",
      "Nükleik Asitler",
      "Genom ve Genetik",
      "Vitaminler ve Mineraller",
      "Hormonlar",
    ],
  },
  {
    name: "Tıbbi Mikrobiyoloji",
    subtopics: [
      "Temel Mikrobiyoloji",
      "Bakteriyoloji",
      "Parazitoloji",
      "Mikoloji",
      "Viroloji",
      "İmmunoloji",
    ],
  },
  {
    name: "Tıbbi Patoloji",
    subtopics: [
      "Hücre",
      "İnflamasyon",
      "İmmun Sistem",
      "Onarım ve Yara İyileşmesi",
      "Hemodinamik Hastalıklar",
      "Neoplazi",
      "Solunum Sistemi",
      "Kardiyovasküler Sistem",
      "Hemopoetik Sistem",
      "Gastrointestinal Sistem",
      "Hepatobilier Sistem",
      "Üriner Sistem",
      "Endokrin Sistem",
      "Kadın Genital Sistemi",
      "Erkek Genital Sistemi",
      "Meme Hastalıkları",
      "Sinir Sistemi",
      "Kas İskelet Sistemi",
      "Deri Hastalıkları",
    ],
  },
  {
    name: "Tıbbi Farmakoloji",
    subtopics: [
      "Genel Farmakoloji",
      "Otonom Sinir Sistemi",
      "Santral Sinir Sistemi",
      "Kardiyovasküler Sistem",
      "Solunum Sistemi",
      "Gastrointestinal Sistem",
      "Endokrin Sistem",
      "Otakoidler",
      "NSAİİ",
      "Kemoterapotikler",
      "Toksikoloji",
    ],
  },
  {
    name: "Dahiliye",
    subtopics: [
      "Hematoloji",
      "Onkoloji",
      "Nefroloji",
      "Kardiyoloji",
      "Göğüs Hastalıkları",
      "Gastroenteroloji",
      "Hepatoloji",
      "Endokrin",
      "Romatoloji",
      "Enfeksiyon Hastalıkları",
      "Allerji-İmmunoloji",
      "Geriatri",
    ],
  },
  {
    name: "Pediatri",
    subtopics: [
      "Yenidoğan",
      "Genetik",
      "Büyüme ve Gelişme",
      "Beslenme",
      "Gastroenteroloji ve Hepatoloji",
      "Nöroloji",
      "Kardiyoloji",
      "Göğüs Hastalıkları",
      "Döküntülü Hastalıklar",
      "Bağışıklama",
      "Allerji",
      "İmmunoloji",
      "Enfeksiyon Hastalıkları",
      "Endokrinoloji",
      "Metabolik Hastalıklar",
      "Hematoloji",
      "Onkoloji",
      "Nefroloji",
      "Romatoloji",
      "Acil Tıp, Zehirlenmeler ve Yoğun Bakım",
      "Çocuk Psikiyatrisi",
      "Çocuk Cerrahisi",
    ],
  },
  {
    name: "Genel Cerrahi",
    subtopics: [
      "Temel Cerrahi",
      "Meme Hastalıkları",
      "Tiroid Hastalıkları",
      "Paratiroid Hastalıkları",
      "Adrenal Bez Hastalıkları",
      "Özefagus",
      "Mide",
      "İnce Barsak",
      "Kolorektal",
      "Appendiks",
      "Anal Kanal ve Perianal Bölge",
      "Karaciğer",
      "Safra Yolu ve Safra Kesesi",
      "Pankreas",
      "Dalak",
      "Karın Duvarı, Periton, Retroperiton ve Mezenter",
      "Fıtık",
      "Sıvı-Elektrolit ve Asit-Baz",
      "Beslenme",
      "Travmaya Yanıt",
      "Şok",
      "Cerrahi Enfeksiyonlar",
      "Yara İyileşmesi",
      "Hemostaz ve Transfüzyon",
      "Travmalı Hastaya Yaklaşım",
      "Yanık",
      "Transplantasyon",
      "Tıp Etiği",
      "Temel Cerrahi-Diğer",
    ],
  },
  {
    name: "Kadın Doğum",
    subtopics: ["Jinekoloji", "Endokrinoloji", "Onkoloji", "Obstetri"],
  },
  {
    name: "Küçük Stajlar",
    subtopics: [
      "Nöroloji",
      "Beyin Cerrahisi",
      "Psikiyatri",
      "Halk Sağlığı",
      "Dermatoloji",
      "Radyoloji",
      "Nükleer Tıp",
      "KBB",
      "Göz Hastalıkları",
      "Ortopedi",
      "FTR",
      "Üroloji",
      "Çocuk Cerrahisi",
      "Kalp Damar Cerrahisi",
      "Göğüs Cerrahisi",
      "Plastik Cerrahi",
      "Anestezi",
      "Acil Tıp ve Zehirlenmeler",
      "Adli Tıp",
    ],
  },
] as const;
